### PR TITLE
Mobile version: about section

### PR DESCRIPTION
**Pull request by barakadanny**
following are different things that have been made in this Pull request:

- Created the skills div in the about section
- created skill details div to give more details about a certain skill in this section (about)

### CODE REVIEW

**Comment by barakadanny** [comment]
note that the official readme file is on the master branch

**Review by cynthiainga — CHANGES_REQUESTED** [review]
Hi @barakadanny, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights

- [ ] All linters are passing :100: :heavy_check_mark: 
- [ ] Good commit history :heavy_check_mark: 
- [ ] Good implementation of the UI :heavy_check_mark: 

## Required Changes ♻️

- [x] Please kindly make your pull request more descriptive, put a short description of the project, and highlight the important point that you did in the project :upside_down_face:.
- [x] Please kindly make sure your pull request has a descriptive name, instead of `about myself` you can say `Mobile version: about section` :+1: :+1: , ... 
- [x] I know that your README.md is already in your master branch but you can just make some modifications to it and commit your changes then we can be able to see if you follow this [template](https://github.com/microverseinc/readme-template/blob/master/README.md) and help to improve it if needed :upside_down_face: :upside_down_face: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by barakadanny** [comment]
Hello @cynthiainga  I have made all the changes, Kindly check if anything else may be needed

**Comment by cynthiainga** [comment]
Hello @barakadanny, good implementation of changes required, so in your README file I can suggest you change the Author, instead of `Author1` you can put your name `Baraka Danny`.

**Comment by barakadanny** [comment]
@cynthiainga , Author name added in readme file

**Review by codecaiine — APPROVED** [review]
Hi @barakadanny , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
 No linters errors :heavy_check_mark:
 Good commit history :heavy_check_mark:
 Good UI implementation :heavy_check_mark:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
